services:
  # N8N service
  n8nserver:
    image: n8nio/n8n:stable
    container_name: n8nserver    
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_SECURE_COOKIE=false
      - N8N_RUNNERS_ENABLED=true
      - N8N_EDITOR_BASE_URL="$N8N_ENDPOINT"
      - WEBHOOK_URL="$N8N_ENDPOINT"
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    depends_on:
      - ngrok        
    restart: unless-stopped
    volumes:
      - /root/n8n_data:/home/node/.n8n

  # Ngrok service
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    ports:
      - "4040:4040"  # Ngrok web interface
    environment:   
       - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--url=$NGROK_WEB_URL"
      - "$NGROK_TUNNEL_ENDPOINT"
    volumes:
      - /root/ngrok_data:/home/ngrok    
    restart: unless-stopped

networks:
  n8n_network:
    driver: bridge

